version: '3.4'

services:
  frontend:
    image: hackathon-webapp
    volumes:
      - ./webapp:/app
    build:
      context: ./webapp
    ports:
      - 8000:8000
    environment:
      VITE_MAGIC_PUBLISHABLE_KEY: ${MAGIC_PUBLISHABLE_KEY}
    network_mode: host
  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - frontend
    network_mode: host
