logging:
  include-application-name: false
spring:
  application:
    name: hackathon-tezos
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:nectart}?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serdTimezone=UTC
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: false #true
#    show-sql: true #false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        enable_lazy_load_no_trans: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
springdoc:
  disable-i18n: true
  api-docs:
    path: /spec.json
  swagger-ui:
    use-root-path: true
    tags-sorter: alpha
    operations-sorter: alpha
error:
  handling:
    full-stacktrace-http-statuses:
    - 5xx
    log-levels:
      4xx: DEBUG
