# Reference: https://github.com/marketplace/actions/setup-node-js-environment 

name: Hardhat Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - name: Cache dependencies
      uses: actions/cache@v2
      working-directory: ./blockchain
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package.json') }}
        restore-keys: npm-

    - name: Install dependencies
      run: yarn
      working-directory: ./blockchain

    - name: Run Test
      run: yarn test
      working-directory: ./blockchain
